### ISSUE TITLE
Refactor all functions and variables to use camelCase 

### ISSUE THREAD

**Issue by dolby360** [dolby360/hex_color_displayer#1]

**Comment by aradbivas** [comment]
Hi, would like to do it.

**Comment by dolby360** [comment]
> Hi, would like to do it.

Thank you very much for your contribution.
You have been assigned to this issue

**Comment by dolby360** [comment]
@aradbivas please note that yesterday I fixed critical bugs. So in order to be able to run this code properly please rebase above master.

**Comment by dolby360** [comment]
Thanks for you contribution
