### ISSUE TITLE
Start fixing linter issues

### ISSUE THREAD

**Issue by dolby360** [dolby360/hex_color_displayer#26]
In order to add eslinter to the pipeline we have to fix all the current issues first. Any help with fixing the issues will be much appreciated. 
To see current issues install the project dependencies first.
```bash
npm install
```
Then run linter with:
```bash
npm run lint
```
Feel free to fix as many as you want. Before making any contribution please check the [contribution guide](https://github.com/dolby360/hex_color_displayer/blob/master/.github/CONTRIBUTING.md).

**Comment by Tamir198** [comment]
I can help with this issue

**Comment by Tamir198** [comment]
Should I ignore this for now or delete this file? 
![image](https://user-images.githubusercontent.com/34707669/194500819-7649d656-4815-4eb2-9342-44c8fa0b8787.png)

Those are all things that are inside the test file (currently there are no tests inside this file).

**Comment by Tamir198** [comment]
What should I do with this line (the path is hex_color_displayer\src\index.jsx line 64):
`this.initializationFinished = true;`

It is not used and gives the `Unused method or property "initializationFinished" of class "HexColorDisplay"` error.

**Comment by dolby360** [comment]
> Should I ignore this for now or delete this file? ![image](https://user-images.githubusercontent.com/34707669/194500819-7649d656-4815-4eb2-9342-44c8fa0b8787.png)
> 
> Those are all things that are inside the test file (currently there are no tests inside this file).

For now, we can tell the linter to not check test file. If you don't know how leave it to me.

**Comment by dolby360** [comment]
> What should I do with this line (the path is hex_color_displayer\src\index.jsx line 64): `this.initializationFinished = true;`
> 
> It is not used and gives the `Unused method or property "initializationFinished" of class "HexColorDisplay"` error.

Is it really not in use? If so delete it:) if not let me know I'll check it out.
