### ISSUE TITLE
For loops should be replaced with  filter, reduce, map, forEach,

### ISSUE THREAD

**Issue by dolby360** [dolby360/hex_color_displayer#9]

**Comment by EladMotzny** [comment]
Can I work on this issue?

**Comment by dolby360** [comment]
@EladMotzny I just added contributing.md file, for more instructions and examples.
Please check it out:
https://github.com/dolby360/hex_color_displayer/blob/master/.github/CONTRIBUTING.md

**Comment by EladMotzny** [comment]
Thanks! I'll be sure to check it out.

**Comment by dolby360** [comment]
@EladMotzny Thank you, please let me know how was the integration experience. If there was any documentation missing.

**Comment by dolby360** [comment]
@EladMotzny Are getting along with this?

**Comment by EladMotzny** [comment]
Hi. Yes, progress is coming slowly but surely. I hope this weekend I will create a PR
